import { APIGateway } from 'aws-sdk';

const gatewayClient = new APIGateway()

const exportType = process.env.AWS_API_EXPORT_TYPE
export class APIGatewayService {
    /**
     * Creates the latest documentation export of this version
     * @param apiId The ID of the API to get the export from
     * @param version The API Docs version
     * @param stage the foundation URI for backwards compatibility
     */
    static async createDocumentationVersion(apiId: string, version: string, stage: string = 'v1'): Promise<void> {
        return new Promise<void>((resolve, reject) => {
            gatewayClient.createDocumentationVersion({
                restApiId: apiId,
                documentationVersion: version,
                stageName: stage,
                description: "Generated by Open API Gateway"
            }, (err, data) => {
                if (!!err) {
                    reject(err)
                    return
                }
                resolve()
            })
        })

    }

    /**
     * Gets the export of the api gateway api docs using the API Gateway ID
     * @param apiId The ID of the API to get the export from
     * @param stage the foundation URI for backwards compatibility
     */
    static async getExport(apiId: string, stage: string = 'v1'): Promise<string> {
        return new Promise<string>((resolve, reject) => {
            gatewayClient.getExport({
                restApiId: apiId,
                stageName: stage,
                accepts: 'application/json',
                exportType: exportType
            }, (err, data) => {
                if (!!err) {
                    reject(err)
                    return
                }
                resolve(data.body.toString())
            })
        })

    }

    /**
     * AWS breaks some Swagger conventions so we need to fix that.
     * @param spec The input Swagger Spec
     */
    static fixAwsNonsense(spec: any): any {
        if (!!spec.servers) {
            spec.servers.forEach(server => {
                if (!!server.variables && !! server.variables.basePath && server.variables.basePath.default && server.variables.basePath.default.startsWith('/')) {
                    server.variables.basePath.default = server.variables.basePath.default.substring(1)
                }
            })
        }
        return spec
    }

}
