Description: "Microservice API and Auth settings"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  StageName:
    Type: String
    Default: v1
  PlumbingBucket:
    Type: String
    Default: openapi-plumbing

Resources:
  # You don't actually need the API, but it does allow you to centralize your auth config, and allows you to add an Open API Spec
  # If you change the name of this Logical ID, then you need to update the Makefile to pull the correct API Gateway ID based on this logical ID.
  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: OpenAPI-Example
      StageName: !Ref StageName
      DefinitionBody:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location:
              Fn::Sub: "s3://${PlumbingBucket}/${AWS::StackName}-openapi.yaml"
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handles the basic request with no need for authentication
      Runtime: go1.x
      Handler: ./dist/main
      Events:
        Get:
          Type: Api
          Properties:
            Path: /
            RestApiId: !Ref ServiceApi
            Method: GET
Outputs:
  GatewayEndpoint:
    Description: "API Prod stage endpoint"
    Value: !Sub "https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
