openapi: 3.0.2
info:
  title: Example
  description: Example Microservice API
  contact:
    email: info@tenmilesquare.com
  version: 1.0.0
tags:
  - name: Home
    description: The basic url usage
  - name: CORS
    description: CORS Support
paths:
  /:
    get:
      tags:
        - Home
      summary: Get Test Object
      description: Returns a simple object with json structure to show the inner workings
      operationId: getTest
      responses:
        '200':
          description: The basic return value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestObject'
        '500':
          description: Internal Server error
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations"

        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    options:
      tags:
        - CORS
      summary: CORS Support
      responses:
        '200':
          description: Default CORS Response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
          content: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: '''OPTIONS,PUT'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
            responseTemplates:
              application/json: |
                {}
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        passthroughBehavior: when_no_match
        type: mock
components:
  schemas:
    TestObject:
      type: object
      properties:
        message:
          type: string
        structure:
          type: string
          